sudo: required
services: 
  - docker
env:
  global: 
    - SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - gem install rake
  - openssl aes-256-cbc -K $encrypted_83262738a0b7_key -iv $encrypted_83262738a0b7_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project wso2-api-microgateway-256019
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials wso2-cluster	 
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fabiowso2/bookstore-microservice:test -f ./microservices/docker/Dockerfile ./microservices

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
