apiVersion: v1
kind: Service
metadata:
  name: bookstore-microgateway-service
spec:
  type: ClusterIP
  selector: 
    component: bookstore-microgateway
  ports:
    - port: 9090
      targetPort: 9090
    
  

