apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /bookstore/
            backend:
              serviceName: bookstore-microgateway-service
              servicePort: 9090
          - path: /v3alpha/
            backend:
              serviceName: etcd-service
              servicePort: 2379